apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-server
  labels:
    app: simple-api-server
spec:
  replicas: 20
  selector:
    matchLabels:
      app: simple-api-server
  template:
    metadata:
      labels:
        app: simple-api-server
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: server
          image: "pcreuwcore.azurecr.io/simpleapi:v1.0.0"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          lifecycle: 
            preStop:
              httpGet:
                path: /api/podTerminate
                port: 3000
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/podReady
              port: http
          readinessProbe:
            httpGet:
              path: /api/podReady
              port: http